### PR TITLE
Proposed symbology fixes

### PR DESCRIPTION
**Pull request by joewheaton**
Hey @philipbaileynar,
I went through and looked at the changes to symbology and business logic @Cashe93 and @CHafen had made or suggested in BaseCamp and what was in repo for Riverscapes Context. I got this dialed in how I want it working for everything but vegetation and roads.

image

I've broken out commits so you can review. Note that I did make some changes to the `Shared` symbology. I did not attempt to add new `*.lyr` files to `Shared`, I just updated a few existing. However, some of the additions might be good candidates...

### CODE REVIEW

**Comment by philipbaileynar** [comment]
@joewheaton clarifying question... Most folks have been heads down on individual models and less concerned with shared. 

Have you done a full sweep of the 3 or 4 model folders and consolidated any potential duplicates into the shared folder?

**Comment by philipbaileynar** [comment]
Nice work. 

Rave is a bit broken right now. I can probably get a release out Monday, but it might be Tuesday.

**Comment by joewheaton** [comment]
No rush @philipbaileynar ... I have it working locally. Note I used the Asotin context

**Comment by joewheaton** [comment]
> @joewheaton clarifying question... Most folks have been heads down on individual models and less concerned with shared. 
> 
> Have you done a full sweep of the 3 or 4 model folders and consolidated any potential duplicates into the shared folder?

No... Will do. There will be some we want different for the same thing. I want to get a little feed back from some others.

**Comment by joewheaton** [comment]
I added two more commits to this Branch and pushed them. Do pull requests include these if they haven't been applied yet?

**Comment by joewheaton** [comment]
As with other changes, just burying my testing of 1.1.0 for each project type in here. Everything worked as expected. One little inconsistency: #62 

[](http://www.youtube.com/watch?v=Iu6ax5KXG4I "")

**Pull request merged**
